### ISSUE TITLE
./configure error

### ISSUE THREAD

**Issue by Reezus** [okias/xf86-input-fujitouch#3]
Hi, so yesterday I installed Mint 16 xfce 32bit on my Fujitsu-Siemens Lifebook P1610 and I'm struggling to get the touchscreen to work. I downloaded this in hopes it'll solve my issue but I can't for my life install this, here's what terminal says http://pastebin.com/9F60RiAw and here's config.log http://pastebin.com/yCt0jMLg , can someone help me? Note - I'm a complete beginner with Linux

**Comment by cinaeco** [comment]
I too received the error "System error while sending DUMMY_DATA to device", and found that problem was that the touchscreen was not on serial port `ttyS0`.

I checked `Xorg.0.log` for which serial port the wacom driver tried to connect to and found `/dev/ttyS4`. Changing the config in #4 to reflect this allowed the touchscreen to work, without needing to run `setserial`.
